version: "2.3"
services:
  baseauth-redis:
    image: redis:7-alpine
    container_name: baseauth-redis
    volumes:
      - ./dockerdata/redis/data:/data
    networks:
      - baseauthnet
    restart: always
    command: redis-server --appendonly yes

  baseauth-postgres:
    image: postgres:16-alpine
    container_name: baseauth-postgres
    environment:
      - POSTGRES_PASSWORD=$BASEAUTH_DB_PASSWORD
      - POSTGRES_USER=$BASEAUTH_DB_USER
      - POSTGRES_DB=$BASEAUTH_DB_NAME
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./dockerdata/postgres/16/data:/var/lib/postgresql/data/pgdata
    networks:
      - baseauthnet
    restart: always

  baseauth-django:
    build: ./src
    container_name: baseauth-django
    environment:
      - POSTGRES_PASSWORD=$BASEAUTH_DB_PASSWORD
      - POSTGRES_USER=$BASEAUTH_DB_USER
      - POSTGRES_DB=$BASEAUTH_DB_NAME
    expose:
      - 8000
    volumes:
      - ./src:/django
      - ./logs:/logs
    networks:
      - baseauthnet
    restart: always

  baseauth-rq-worker-1:
    build: ./src
    image: baseauth-django
    container_name: baseauth-rq-worker-1
    environment:
      - POSTGRES_PASSWORD=$BASEAUTH_DB_PASSWORD
      - POSTGRES_USER=$BASEAUTH_DB_USER
      - POSTGRES_DB=$BASEAUTH_DB_NAME
    volumes_from:
      - baseauth-django
    networks:
      - baseauthnet
    restart: always
    command: python manage.py rqworker --with-scheduler default

  baseauth-rq-worker-2:
    build: ./src
    image: baseauth-django
    container_name: baseauth-rq-worker-2
    environment:
      - POSTGRES_PASSWORD=$BASEAUTH_DB_PASSWORD
      - POSTGRES_USER=$BASEAUTH_DB_USER
      - POSTGRES_DB=$BASEAUTH_DB_NAME
    volumes_from:
      - baseauth-django
    networks:
      - baseauthnet
    restart: always
    command: python manage.py rqworker default

  baseauth-cron:
    image: paradoxon/alpine-cron
    container_name: baseauth-cron
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/cron/crontab:/tmp/crontab
    network_mode: "none"
    restart: always

networks:
  baseauthnet:
